-- MySQL Script generated by MySQL Workbench
-- 04/09/15 13:21:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gamcultt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gamcultt` ;

-- -----------------------------------------------------
-- Schema gamcultt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamcultt` DEFAULT CHARACTER SET utf8 ;
USE `gamcultt` ;

-- -----------------------------------------------------
-- Table `gamcultt`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`alumno` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`alumno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NOT NULL,
  `materno` VARCHAR(45) NOT NULL,
  `edad` INT(11) NOT NULL,
  `nombre_tutor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`profesor` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`profesor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NOT NULL,
  `materno` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`casa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`casa` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`casa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(85) NOT NULL,
  `direccion` VARCHAR(105) NOT NULL,
  `telefono` VARCHAR(85) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `informacion` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`sala` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`sala` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `casa` INT(11) NOT NULL,
  `nombre` VARCHAR(95) NOT NULL,
  `capacidad` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sala_casa1_idx` (`casa` ASC),
  CONSTRAINT `fk_sala_casa1`
    FOREIGN KEY (`casa`)
    REFERENCES `gamcultt`.`casa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`taller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`taller` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`taller` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria_id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`clase` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`clase` (
  `profesor` INT(11) NOT NULL,
  `taller` INT(11) NOT NULL,
  `sala` INT(11) NOT NULL,
  `costo` DECIMAL(6,2) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`profesor`, `taller`),
  INDEX `fk_alumno_has_profesor_profesor1_idx` (`profesor` ASC),
  INDEX `fk_alumno_has_profesor_taller1_idx` (`taller` ASC),
  INDEX `fk_alumno_has_profesor_sala1_idx` (`sala` ASC),
  CONSTRAINT `fk_alumno_has_profesor_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `gamcultt`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_profesor_sala1`
    FOREIGN KEY (`sala`)
    REFERENCES `gamcultt`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_profesor_taller1`
    FOREIGN KEY (`taller`)
    REFERENCES `gamcultt`.`taller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`alumno_clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`alumno_clase` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`alumno_clase` (
  `alumno` INT(11) NOT NULL,
  `clase_profesor` INT(11) NOT NULL,
  `clase_taller` INT(11) NOT NULL,
  `alumno_clasecol` VARCHAR(45) NULL,
  PRIMARY KEY (`alumno`, `clase_profesor`, `clase_taller`),
  INDEX `fk_alumno_has_clase_clase2_idx` (`clase_profesor` ASC, `clase_taller` ASC),
  INDEX `fk_alumno_has_clase_alumno2_idx` (`alumno` ASC),
  CONSTRAINT `fk_alumno_has_clase_alumno2`
    FOREIGN KEY (`alumno`)
    REFERENCES `gamcultt`.`alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_clase_clase2`
    FOREIGN KEY (`clase_profesor` , `clase_taller`)
    REFERENCES `gamcultt`.`clase` (`profesor` , `taller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`casa_has_taller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`casa_has_taller` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`casa_has_taller` (
  `casa` INT(11) NOT NULL,
  `taller` INT(11) NOT NULL,
  `casa_has_tallercol` VARCHAR(45) NULL,
  PRIMARY KEY (`casa`, `taller`),
  INDEX `fk_CASA_has_taller_taller1_idx` (`taller` ASC),
  INDEX `fk_CASA_has_taller_CASA1_idx` (`casa` ASC),
  CONSTRAINT `fk_CASA_has_taller_CASA1`
    FOREIGN KEY (`casa`)
    REFERENCES `gamcultt`.`casa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CASA_has_taller_taller1`
    FOREIGN KEY (`taller`)
    REFERENCES `gamcultt`.`taller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`encargado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`encargado` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`encargado` (
  `id` INT(11) NOT NULL,
  `casa` INT(11) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_encargado_Usuario1_idx` (`id` ASC),
  INDEX `fk_encargado_casa1_idx` (`casa` ASC),
  CONSTRAINT `fk_encargado_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `gamcultt`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encargado_casa1`
    FOREIGN KEY (`casa`)
    REFERENCES `gamcultt`.`casa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`evento` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sala` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `informacion` TEXT NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(105) NOT NULL,
  `asistencia_estimada` INT(11) NOT NULL,
  `asistencia_real` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_sala1_idx` (`sala` ASC),
  CONSTRAINT `fk_evento_sala1`
    FOREIGN KEY (`sala`)
    REFERENCES `gamcultt`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`galeria_casa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`galeria_casa` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`galeria_casa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `casa` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extencion` VARCHAR(5) NOT NULL,
  `path` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galeria_CASA1_idx` (`casa` ASC),
  CONSTRAINT `fk_galeria_CASA1`
    FOREIGN KEY (`casa`)
    REFERENCES `gamcultt`.`casa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`galeria_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`galeria_evento` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`galeria_evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `evento` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extencion` VARCHAR(5) NOT NULL,
  `ruta` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galeria_evento_evento1_idx` (`evento` ASC),
  CONSTRAINT `fk_galeria_evento_evento1`
    FOREIGN KEY (`evento`)
    REFERENCES `gamcultt`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`galeria_taller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`galeria_taller` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`galeria_taller` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `taller` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extencion` VARCHAR(5) NOT NULL,
  `path` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galeria_taller_taller1_idx` (`taller` ASC),
  CONSTRAINT `fk_galeria_taller_taller1`
    FOREIGN KEY (`taller`)
    REFERENCES `gamcultt`.`taller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`propuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`propuesta` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`propuesta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `encargado` INT(11) NOT NULL,
  `representante` VARCHAR(105) NOT NULL,
  `objetivo` TEXT NOT NULL,
  `personas` INT(11) NULL DEFAULT NULL,
  `descripcion` TEXT NOT NULL,
  `correo` VARCHAR(85) NOT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  `asistencia_estimada` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_propuesta_encargado1_idx` (`encargado` ASC),
  CONSTRAINT `fk_propuesta_encargado1`
    FOREIGN KEY (`encargado`)
    REFERENCES `gamcultt`.`encargado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
