package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AlumnoClase generated by hbm2java
 */
@Entity
@Table(name="alumno_clase"
    ,catalog="gamcultt"
)
public class AlumnoClase  implements java.io.Serializable {


     private AlumnoClaseId id;
     private Clase clase;
     private Alumno alumno;
     private String alumnoClasecol;

    public AlumnoClase() {
    }

	
    public AlumnoClase(AlumnoClaseId id, Clase clase, Alumno alumno) {
        this.id = id;
        this.clase = clase;
        this.alumno = alumno;
    }
    public AlumnoClase(AlumnoClaseId id, Clase clase, Alumno alumno, String alumnoClasecol) {
       this.id = id;
       this.clase = clase;
       this.alumno = alumno;
       this.alumnoClasecol = alumnoClasecol;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="alumno", column=@Column(name="alumno", nullable=false) ), 
        @AttributeOverride(name="claseProfesor", column=@Column(name="clase_profesor", nullable=false) ), 
        @AttributeOverride(name="claseTaller", column=@Column(name="clase_taller", nullable=false) ) } )
    public AlumnoClaseId getId() {
        return this.id;
    }
    
    public void setId(AlumnoClaseId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="clase_profesor", referencedColumnName="profesor", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="clase_taller", referencedColumnName="taller", nullable=false, insertable=false, updatable=false) } )
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="alumno", nullable=false, insertable=false, updatable=false)
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    
    @Column(name="alumno_clasecol", length=45)
    public String getAlumnoClasecol() {
        return this.alumnoClasecol;
    }
    
    public void setAlumnoClasecol(String alumnoClasecol) {
        this.alumnoClasecol = alumnoClasecol;
    }




}


