package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlumnoClaseId generated by hbm2java
 */
@Embeddable
public class AlumnoClaseId  implements java.io.Serializable {


     private int alumno;
     private int claseProfesor;
     private int claseTaller;

    public AlumnoClaseId() {
    }

    public AlumnoClaseId(int alumno, int claseProfesor, int claseTaller) {
       this.alumno = alumno;
       this.claseProfesor = claseProfesor;
       this.claseTaller = claseTaller;
    }
   


    @Column(name="alumno", nullable=false)
    public int getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(int alumno) {
        this.alumno = alumno;
    }


    @Column(name="clase_profesor", nullable=false)
    public int getClaseProfesor() {
        return this.claseProfesor;
    }
    
    public void setClaseProfesor(int claseProfesor) {
        this.claseProfesor = claseProfesor;
    }


    @Column(name="clase_taller", nullable=false)
    public int getClaseTaller() {
        return this.claseTaller;
    }
    
    public void setClaseTaller(int claseTaller) {
        this.claseTaller = claseTaller;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnoClaseId) ) return false;
		 AlumnoClaseId castOther = ( AlumnoClaseId ) other; 
         
		 return (this.getAlumno()==castOther.getAlumno())
 && (this.getClaseProfesor()==castOther.getClaseProfesor())
 && (this.getClaseTaller()==castOther.getClaseTaller());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAlumno();
         result = 37 * result + this.getClaseProfesor();
         result = 37 * result + this.getClaseTaller();
         return result;
   }   


}


