package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name="alumno"
    ,catalog="gamcultt"
)
public class Alumno  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String paterno;
     private String materno;
     private int edad;
     private String nombreTutor;
     private Set<AlumnoClase> alumnoClases = new HashSet<AlumnoClase>(0);

    public Alumno() {
    }

	
    public Alumno(String nombre, String paterno, String materno, int edad) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.edad = edad;
    }
    public Alumno(String nombre, String paterno, String materno, int edad, String nombreTutor, Set<AlumnoClase> alumnoClases) {
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.edad = edad;
       this.nombreTutor = nombreTutor;
       this.alumnoClases = alumnoClases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="paterno", nullable=false, length=45)
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }

    
    @Column(name="materno", nullable=false, length=45)
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }

    
    @Column(name="edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }

    
    @Column(name="nombre_tutor", length=45)
    public String getNombreTutor() {
        return this.nombreTutor;
    }
    
    public void setNombreTutor(String nombreTutor) {
        this.nombreTutor = nombreTutor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="alumno")
    public Set<AlumnoClase> getAlumnoClases() {
        return this.alumnoClases;
    }
    
    public void setAlumnoClases(Set<AlumnoClase> alumnoClases) {
        this.alumnoClases = alumnoClases;
    }




}


