package mx.ipn.escom.entidades;
// Generated 8/04/2015 05:34:35 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "gamcultt")
public class Alumno implements java.io.Serializable {

    @Id    
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter Integer id;
    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;
    @Column(name = "paterno", nullable = false, length = 45)
    @Getter @Setter private String paterno;
    @Column(name = "materno", nullable = false, length = 45)
    @Getter @Setter private String materno;
    @Column(name = "edad", nullable = false)
    @Getter @Setter private int edad;
    @Column(name = "nombre_tutor", length = 45)
    @Getter @Setter private String nombreTutor;
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "alumno_clase", catalog = "gamcultt", joinColumns = {
    @JoinColumn(name = "alumno", nullable = false, updatable = false)}, inverseJoinColumns = {
    @JoinColumn(name = "clase_profesor", nullable = false, updatable = false)})
    
    @Getter @Setter private List<Clase> clases;

    public Alumno() {
    }

    public Alumno(String nombre, String paterno, String materno, int edad) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.edad = edad;
    }

    public Alumno(String nombre, String paterno, String materno, int edad, String nombreTutor, List<Clase> clases) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.edad = edad;
        this.nombreTutor = nombreTutor;
        this.clases = clases;
    }

    
    
    
   }
