package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Casa generated by hbm2java
 */
@Entity
@Table(name="casa"
    ,catalog="gamcultt"
)
public class Casa  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String direccion;
     private String telefono;
     private String horario;
     private String informacion;
     private Set<GaleriaCasa> galeriaCasas = new HashSet<GaleriaCasa>(0);
     private Set<Sala> salas = new HashSet<Sala>(0);
     private Set<CasaHasTaller> casaHasTallers = new HashSet<CasaHasTaller>(0);
     private Set<Encargado> encargados = new HashSet<Encargado>(0);

    public Casa() {
    }

	
    public Casa(String nombre, String direccion, String telefono, String horario, String informacion) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.horario = horario;
        this.informacion = informacion;
    }
    public Casa(String nombre, String direccion, String telefono, String horario, String informacion, Set<GaleriaCasa> galeriaCasas, Set<Sala> salas, Set<CasaHasTaller> casaHasTallers, Set<Encargado> encargados) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.horario = horario;
       this.informacion = informacion;
       this.galeriaCasas = galeriaCasas;
       this.salas = salas;
       this.casaHasTallers = casaHasTallers;
       this.encargados = encargados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=85)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", nullable=false, length=105)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", nullable=false, length=85)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="horario", nullable=false, length=45)
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }

    
    @Column(name="informacion", nullable=false, length=65535)
    public String getInformacion() {
        return this.informacion;
    }
    
    public void setInformacion(String informacion) {
        this.informacion = informacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casa")
    public Set<GaleriaCasa> getGaleriaCasas() {
        return this.galeriaCasas;
    }
    
    public void setGaleriaCasas(Set<GaleriaCasa> galeriaCasas) {
        this.galeriaCasas = galeriaCasas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casa")
    public Set<Sala> getSalas() {
        return this.salas;
    }
    
    public void setSalas(Set<Sala> salas) {
        this.salas = salas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casa")
    public Set<CasaHasTaller> getCasaHasTallers() {
        return this.casaHasTallers;
    }
    
    public void setCasaHasTallers(Set<CasaHasTaller> casaHasTallers) {
        this.casaHasTallers = casaHasTallers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casa")
    public Set<Encargado> getEncargados() {
        return this.encargados;
    }
    
    public void setEncargados(Set<Encargado> encargados) {
        this.encargados = encargados;
    }




}


