package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CasaHasTaller generated by hbm2java
 */
@Entity
@Table(name="casa_has_taller"
    ,catalog="gamcultt"
)
public class CasaHasTaller  implements java.io.Serializable {


     private CasaHasTallerId id;
     private Taller taller;
     private Casa casa;
     private String casaHasTallercol;

    public CasaHasTaller() {
    }

	
    public CasaHasTaller(CasaHasTallerId id, Taller taller, Casa casa) {
        this.id = id;
        this.taller = taller;
        this.casa = casa;
    }
    public CasaHasTaller(CasaHasTallerId id, Taller taller, Casa casa, String casaHasTallercol) {
       this.id = id;
       this.taller = taller;
       this.casa = casa;
       this.casaHasTallercol = casaHasTallercol;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="casa", column=@Column(name="casa", nullable=false) ), 
        @AttributeOverride(name="taller", column=@Column(name="taller", nullable=false) ) } )
    public CasaHasTallerId getId() {
        return this.id;
    }
    
    public void setId(CasaHasTallerId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="taller", nullable=false, insertable=false, updatable=false)
    public Taller getTaller() {
        return this.taller;
    }
    
    public void setTaller(Taller taller) {
        this.taller = taller;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="casa", nullable=false, insertable=false, updatable=false)
    public Casa getCasa() {
        return this.casa;
    }
    
    public void setCasa(Casa casa) {
        this.casa = casa;
    }

    
    @Column(name="casa_has_tallercol", length=45)
    public String getCasaHasTallercol() {
        return this.casaHasTallercol;
    }
    
    public void setCasaHasTallercol(String casaHasTallercol) {
        this.casaHasTallercol = casaHasTallercol;
    }




}


