package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CasaHasTallerId generated by hbm2java
 */
@Embeddable
public class CasaHasTallerId  implements java.io.Serializable {


     private int casa;
     private int taller;

    public CasaHasTallerId() {
    }

    public CasaHasTallerId(int casa, int taller) {
       this.casa = casa;
       this.taller = taller;
    }
   


    @Column(name="casa", nullable=false)
    public int getCasa() {
        return this.casa;
    }
    
    public void setCasa(int casa) {
        this.casa = casa;
    }


    @Column(name="taller", nullable=false)
    public int getTaller() {
        return this.taller;
    }
    
    public void setTaller(int taller) {
        this.taller = taller;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CasaHasTallerId) ) return false;
		 CasaHasTallerId castOther = ( CasaHasTallerId ) other; 
         
		 return (this.getCasa()==castOther.getCasa())
 && (this.getTaller()==castOther.getTaller());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCasa();
         result = 37 * result + this.getTaller();
         return result;
   }   


}


