package mx.ipn.escom.entidades;
// Generated 8/04/2015 05:34:35 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name = "clase", catalog = "gamcultt"
)
public class Clase implements java.io.Serializable {

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "profesor", column = @Column(name = "profesor", nullable = false)),
        @AttributeOverride(name = "taller", column = @Column(name = "taller", nullable = false))})
    @Getter
    @Setter

    private ClaseId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "profesor", nullable = false, insertable = false, updatable = false)
    @Getter
    @Setter
    private Profesor profesor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sala", nullable = false)
    @Getter
    @Setter
    private Sala sala;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "taller", nullable = false, insertable = false, updatable = false)
    @Getter
    @Setter
    private Taller taller;

    @Column(name = "costo", nullable = false, precision = 6)
    @Getter
    @Setter
    private BigDecimal costo;

    @Column(name = "horario", nullable = false, length = 45)
    @Getter
    @Setter
    private String horario;

    @Column(name = "status", nullable = false)
    @Getter
    @Setter
    private int status;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "alumno_clase", catalog = "gamcultt", joinColumns = {
        @JoinColumn(name = "clase_profesor", nullable = false, updatable = false),
        @JoinColumn(name = "clase_taller", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "alumno", nullable = false, updatable = false)})
    @Getter
    @Setter
    private List<Alumno> alumnos;

    public Clase() {
    }

    public Clase(ClaseId id, Profesor profesor, Sala sala, Taller taller, BigDecimal costo, String horario, int status) {
        this.id = id;
        this.profesor = profesor;
        this.sala = sala;
        this.taller = taller;
        this.costo = costo;
        this.horario = horario;
        this.status = status;
    }

    public Clase(ClaseId id, Profesor profesor, Sala sala, Taller taller, BigDecimal costo, String horario, int status, List<Alumno> alumnos) {
        this.id = id;
        this.profesor = profesor;
        this.sala = sala;
        this.taller = taller;
        this.costo = costo;
        this.horario = horario;
        this.status = status;
        this.alumnos = alumnos;
    }

}
