package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name="clase"
    ,catalog="gamcultt"
)
public class Clase  implements java.io.Serializable {


     private ClaseId id;
     private Profesor profesor;
     private Sala sala;
     private Taller taller;
     private BigDecimal costo;
     private String horario;
     private int status;
     private Set<AlumnoClase> alumnoClases = new HashSet<AlumnoClase>(0);

    public Clase() {
    }

	
    public Clase(ClaseId id, Profesor profesor, Sala sala, Taller taller, BigDecimal costo, String horario, int status) {
        this.id = id;
        this.profesor = profesor;
        this.sala = sala;
        this.taller = taller;
        this.costo = costo;
        this.horario = horario;
        this.status = status;
    }
    public Clase(ClaseId id, Profesor profesor, Sala sala, Taller taller, BigDecimal costo, String horario, int status, Set<AlumnoClase> alumnoClases) {
       this.id = id;
       this.profesor = profesor;
       this.sala = sala;
       this.taller = taller;
       this.costo = costo;
       this.horario = horario;
       this.status = status;
       this.alumnoClases = alumnoClases;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="profesor", column=@Column(name="profesor", nullable=false) ), 
        @AttributeOverride(name="taller", column=@Column(name="taller", nullable=false) ) } )
    public ClaseId getId() {
        return this.id;
    }
    
    public void setId(ClaseId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesor", nullable=false, insertable=false, updatable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sala", nullable=false)
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="taller", nullable=false, insertable=false, updatable=false)
    public Taller getTaller() {
        return this.taller;
    }
    
    public void setTaller(Taller taller) {
        this.taller = taller;
    }

    
    @Column(name="costo", nullable=false, precision=6)
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    
    @Column(name="horario", nullable=false, length=45)
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clase")
    public Set<AlumnoClase> getAlumnoClases() {
        return this.alumnoClases;
    }
    
    public void setAlumnoClases(Set<AlumnoClase> alumnoClases) {
        this.alumnoClases = alumnoClases;
    }




}


