package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Encargado generated by hbm2java
 */
@Entity
@Table(name="encargado"
    ,catalog="gamcultt"
)
public class Encargado  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private Casa casa;
     private String telefono;
     private Set<Propuesta> propuestas = new HashSet<Propuesta>(0);

    public Encargado() {
    }

	
    public Encargado(Usuario usuario, Casa casa) {
        this.usuario = usuario;
        this.casa = casa;
    }
    public Encargado(Usuario usuario, Casa casa, String telefono, Set<Propuesta> propuestas) {
       this.usuario = usuario;
       this.casa = casa;
       this.telefono = telefono;
       this.propuestas = propuestas;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="usuario"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="casa", nullable=false)
    public Casa getCasa() {
        return this.casa;
    }
    
    public void setCasa(Casa casa) {
        this.casa = casa;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="encargado")
    public Set<Propuesta> getPropuestas() {
        return this.propuestas;
    }
    
    public void setPropuestas(Set<Propuesta> propuestas) {
        this.propuestas = propuestas;
    }




}


