package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name="evento"
    ,catalog="gamcultt"
)
public class Evento  implements java.io.Serializable {


     private Integer id;
     private Sala sala;
     private String nombre;
     private Date fechaInicio;
     private Date fechaFin;
     private String informacion;
     private String horario;
     private String direccion;
     private int asistenciaEstimada;
     private Integer asistenciaReal;
     private int status;
     private Set<GaleriaEvento> galeriaEventos = new HashSet<GaleriaEvento>(0);

    public Evento() {
    }

	
    public Evento(Sala sala, String nombre, Date fechaInicio, Date fechaFin, String informacion, String horario, String direccion, int asistenciaEstimada, int status) {
        this.sala = sala;
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.informacion = informacion;
        this.horario = horario;
        this.direccion = direccion;
        this.asistenciaEstimada = asistenciaEstimada;
        this.status = status;
    }
    public Evento(Sala sala, String nombre, Date fechaInicio, Date fechaFin, String informacion, String horario, String direccion, int asistenciaEstimada, Integer asistenciaReal, int status, Set<GaleriaEvento> galeriaEventos) {
       this.sala = sala;
       this.nombre = nombre;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.informacion = informacion;
       this.horario = horario;
       this.direccion = direccion;
       this.asistenciaEstimada = asistenciaEstimada;
       this.asistenciaReal = asistenciaReal;
       this.status = status;
       this.galeriaEventos = galeriaEventos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sala", nullable=false)
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="informacion", nullable=false, length=65535)
    public String getInformacion() {
        return this.informacion;
    }
    
    public void setInformacion(String informacion) {
        this.informacion = informacion;
    }

    
    @Column(name="horario", nullable=false, length=45)
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }

    
    @Column(name="direccion", nullable=false, length=105)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="asistencia_estimada", nullable=false)
    public int getAsistenciaEstimada() {
        return this.asistenciaEstimada;
    }
    
    public void setAsistenciaEstimada(int asistenciaEstimada) {
        this.asistenciaEstimada = asistenciaEstimada;
    }

    
    @Column(name="asistencia_real")
    public Integer getAsistenciaReal() {
        return this.asistenciaReal;
    }
    
    public void setAsistenciaReal(Integer asistenciaReal) {
        this.asistenciaReal = asistenciaReal;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evento")
    public Set<GaleriaEvento> getGaleriaEventos() {
        return this.galeriaEventos;
    }
    
    public void setGaleriaEventos(Set<GaleriaEvento> galeriaEventos) {
        this.galeriaEventos = galeriaEventos;
    }




}


