package mx.ipn.escom.entidades;
// Generated 8/04/2015 05:34:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GaleriaTaller generated by hbm2java
 */
@Entity
@Table(name="galeria_taller"
    ,catalog="gamcultt"
)
public class GaleriaTaller  implements java.io.Serializable {


     private Integer id;
     private Taller taller;
     private String nombre;
     private String extencion;
     private String path;

    public GaleriaTaller() {
    }

    public GaleriaTaller(Taller taller, String nombre, String extencion, String path) {
       this.taller = taller;
       this.nombre = nombre;
       this.extencion = extencion;
       this.path = path;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="taller", nullable=false)
    public Taller getTaller() {
        return this.taller;
    }
    
    public void setTaller(Taller taller) {
        this.taller = taller;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="extencion", nullable=false, length=5)
    public String getExtencion() {
        return this.extencion;
    }
    
    public void setExtencion(String extencion) {
        this.extencion = extencion;
    }

    
    @Column(name="path", nullable=false, length=85)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


