package mx.ipn.escom.entidades;
// Generated 8/04/2015 05:34:35 PM by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;


/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name = "profesor", catalog = "gamcultt"
)
public class Profesor implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;
    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;
    @Column(name = "paterno", nullable = false, length = 45)
    @Getter @Setter private String paterno;
    @Column(name = "materno", nullable = false, length = 45)
    @Getter @Setter private String materno;
    @Column(name = "correo", nullable = false, length = 45)
    @Getter @Setter private String correo;
    @Column(name = "telefono", length = 45)
    @Getter @Setter private String telefono;
    @Column(name = "celular", length = 45)
    @Getter @Setter private String celular;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "profesor")
    @Getter @Setter private List<Clase> clases;

    public Profesor() {
    }

    public Profesor(String nombre, String paterno, String materno, String correo) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.correo = correo;
    }

    public Profesor(String nombre, String paterno, String materno, String correo, String telefono, String celular, List<Clase> clases) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.correo = correo;
        this.telefono = telefono;
        this.celular = celular;
        this.clases = clases;
    }


}
