package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Propuesta generated by hbm2java
 */
@Entity
@Table(name="propuesta"
    ,catalog="gamcultt"
)
public class Propuesta  implements java.io.Serializable {


     private Integer id;
     private Encargado encargado;
     private String representante;
     private String objetivo;
     private Integer personas;
     private String descripcion;
     private String correo;
     private String telefono;
     private int asistenciaEstimada;

    public Propuesta() {
    }

	
    public Propuesta(Encargado encargado, String representante, String objetivo, String descripcion, String correo, int asistenciaEstimada) {
        this.encargado = encargado;
        this.representante = representante;
        this.objetivo = objetivo;
        this.descripcion = descripcion;
        this.correo = correo;
        this.asistenciaEstimada = asistenciaEstimada;
    }
    public Propuesta(Encargado encargado, String representante, String objetivo, Integer personas, String descripcion, String correo, String telefono, int asistenciaEstimada) {
       this.encargado = encargado;
       this.representante = representante;
       this.objetivo = objetivo;
       this.personas = personas;
       this.descripcion = descripcion;
       this.correo = correo;
       this.telefono = telefono;
       this.asistenciaEstimada = asistenciaEstimada;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="encargado", nullable=false)
    public Encargado getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(Encargado encargado) {
        this.encargado = encargado;
    }

    
    @Column(name="representante", nullable=false, length=105)
    public String getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(String representante) {
        this.representante = representante;
    }

    
    @Column(name="objetivo", nullable=false, length=65535)
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }

    
    @Column(name="personas")
    public Integer getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Integer personas) {
        this.personas = personas;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="correo", nullable=false, length=85)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="telefono", length=25)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="asistencia_estimada", nullable=false)
    public int getAsistenciaEstimada() {
        return this.asistenciaEstimada;
    }
    
    public void setAsistenciaEstimada(int asistenciaEstimada) {
        this.asistenciaEstimada = asistenciaEstimada;
    }




}


