package mx.ipn.escom.entidades;
// Generated 8/04/2015 05:34:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name="sala"
    ,catalog="gamcultt"
)
public class Sala  implements java.io.Serializable {


     private Integer id;
     private Casa casa;
     private String nombre;
     private int capacidad;
     private Set<Clase> clases = new HashSet<Clase>(0);
     private Set<Evento> eventos = new HashSet<Evento>(0);

    public Sala() {
    }

	
    public Sala(Casa casa, String nombre, int capacidad) {
        this.casa = casa;
        this.nombre = nombre;
        this.capacidad = capacidad;
    }
    public Sala(Casa casa, String nombre, int capacidad, Set<Clase> clases, Set<Evento> eventos) {
       this.casa = casa;
       this.nombre = nombre;
       this.capacidad = capacidad;
       this.clases = clases;
       this.eventos = eventos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="casa", nullable=false)
    public Casa getCasa() {
        return this.casa;
    }
    
    public void setCasa(Casa casa) {
        this.casa = casa;
    }

    
    @Column(name="nombre", nullable=false, length=95)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="capacidad", nullable=false)
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sala")
    public Set<Clase> getClases() {
        return this.clases;
    }
    
    public void setClases(Set<Clase> clases) {
        this.clases = clases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sala")
    public Set<Evento> getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set<Evento> eventos) {
        this.eventos = eventos;
    }




}


