package mx.ipn.escom.entidades;
// Generated 8/04/2015 05:34:35 PM by Hibernate Tools 4.3.1



import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name="sala"
    ,catalog="gamcultt"
)
public class Sala  implements java.io.Serializable {

  @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
     @Getter @Setter private Integer id;
  
  @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="casa", nullable=false)
     @Getter @Setter private Casa casa;
  
  @Column(name="nombre", nullable=false, length=95)
     @Getter @Setter private String nombre;
  
  @Column(name="capacidad", nullable=false)
     @Getter @Setter private int capacidad;
     
     @OneToMany(fetch=FetchType.LAZY, mappedBy="sala")
     @Getter @Setter private List<Clase> clases;
     
     @OneToMany(fetch=FetchType.LAZY, mappedBy="sala")
     @Getter @Setter private List<Evento> eventos;

    public Sala() {
    }

	
    public Sala(Casa casa, String nombre, int capacidad) {
        this.casa = casa;
        this.nombre = nombre;
        this.capacidad = capacidad;
    }
    public Sala(Casa casa, String nombre, int capacidad, List<Clase> clases, List<Evento> eventos) {
       this.casa = casa;
       this.nombre = nombre;
       this.capacidad = capacidad;
       this.clases = clases;
       this.eventos = eventos;
    }
   
   
    



}


