package mx.ipn.escom.entidades;
// Generated 8/04/2015 05:34:35 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Taller generated by hbm2java
 */
@Entity
@Table(name = "taller", catalog = "gamcultt"
)
public class Taller implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;
    @Column(name = "categoria_id", nullable = false)
    @Getter @Setter private int categoriaId;
    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;
    @Column(name = "descripcion", nullable = false, length = 65535)
    @Getter @Setter private String descripcion;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taller")
    @Getter @Setter private List<GaleriaTaller> galeriaTallers;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taller")
    @Getter @Setter private List<Clase> clases;

    public Taller() {
    }

    public Taller(int categoriaId, String nombre, String descripcion) {
        this.categoriaId = categoriaId;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }

    public Taller(int categoriaId, String nombre, String descripcion, List<GaleriaTaller> galeriaTallers, List<Clase> clases) {
        this.categoriaId = categoriaId;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.galeriaTallers = galeriaTallers;
        this.clases = clases;
    }

}
