package mx.ipn.escom.entidades;
// Generated 9/04/2015 01:23:35 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Taller generated by hbm2java
 */
@Entity
@Table(name="taller"
    ,catalog="gamcultt"
)
public class Taller  implements java.io.Serializable {


     private Integer id;
     private int categoriaId;
     private String nombre;
     private String descripcion;
     private Set<GaleriaTaller> galeriaTallers = new HashSet<GaleriaTaller>(0);
     private Set<CasaHasTaller> casaHasTallers = new HashSet<CasaHasTaller>(0);
     private Set<Clase> clases = new HashSet<Clase>(0);

    public Taller() {
    }

	
    public Taller(int categoriaId, String nombre, String descripcion) {
        this.categoriaId = categoriaId;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Taller(int categoriaId, String nombre, String descripcion, Set<GaleriaTaller> galeriaTallers, Set<CasaHasTaller> casaHasTallers, Set<Clase> clases) {
       this.categoriaId = categoriaId;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.galeriaTallers = galeriaTallers;
       this.casaHasTallers = casaHasTallers;
       this.clases = clases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="categoria_id", nullable=false)
    public int getCategoriaId() {
        return this.categoriaId;
    }
    
    public void setCategoriaId(int categoriaId) {
        this.categoriaId = categoriaId;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taller")
    public Set<GaleriaTaller> getGaleriaTallers() {
        return this.galeriaTallers;
    }
    
    public void setGaleriaTallers(Set<GaleriaTaller> galeriaTallers) {
        this.galeriaTallers = galeriaTallers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taller")
    public Set<CasaHasTaller> getCasaHasTallers() {
        return this.casaHasTallers;
    }
    
    public void setCasaHasTallers(Set<CasaHasTaller> casaHasTallers) {
        this.casaHasTallers = casaHasTallers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taller")
    public Set<Clase> getClases() {
        return this.clases;
    }
    
    public void setClases(Set<Clase> clases) {
        this.clases = clases;
    }




}


