package mx.ipn.escom.entidades;
// Generated 8/04/2015 05:34:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="gamcultt"
)
public class Usuario  implements java.io.Serializable {

  @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
     @Getter @Setter private Integer id;
  
  @Column(name="Nombre", length=45)
     @Getter @Setter private String nombre;
  
  
  @Column(name="apellido_paterno", length=45)
     @Getter @Setter private String apellidoPaterno;
  
  @Column(name="apellido_materno", length=45)
     @Getter @Setter private String apellidoMaterno;
  
  @Column(name="correo", length=45)
     @Getter @Setter private String correo;
  
  @Column(name="tipo")
     @Getter @Setter private Boolean tipo;
  
  @OneToOne(fetch=FetchType.LAZY, mappedBy="usuario")
     @Getter @Setter private Encargado encargado;

    public Usuario() {
    }

    public Usuario(String nombre, String apellidoPaterno, String apellidoMaterno, String correo, Boolean tipo, Encargado encargado) {
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correo = correo;
       this.tipo = tipo;
       this.encargado = encargado;
    }
   
   
    

}


